// Generated by Wrangler on Sat Oct 05 2024 02:33:52 GMT+0530 (India Standard Time)
// by running `wrangler types`

export interface Env {
	CMS_URL: string
	SPOTIFY_CLIENT_ID: string
	SPOTIFY_CLIENT_SECRET: string
	SPOTIFY_REFRESH_TOKEN: string
}
